In [21]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import random as rd

In [22]:
ds_heart = pd.read_csv(r"E:\dataset\heart.csv", sep=",")

In [23]:
ds = pd.read_csv(r"E:\dataset\data.csv", sep=",", low_memory=False)

In [24]:
ds.head()

,stn_code,sampling_date,state,location,agency,type,so2,no2,rspm,spm,location_monitoring_station,pm2_5,date
0,150,February - M021990,Andhra Pradesh,Hyderabad,NaN,"Residential, Rural and other Areas",4.8,17.4,NaN,NaN,NaN,NaN,01-02-1990
1,151,February - M021990,Andhra Pradesh,Hyderabad,NaN,Industrial Area,3.1,7.0,NaN,NaN,NaN,NaN,01-02-1990
2,152,February - M021990,Andhra Pradesh,Hyderabad,NaN,"Residential, Rural and other Areas",6.2,28.5,NaN,NaN,NaN,NaN,01-02-1990
3,150,March - M031990,Andhra Pradesh,Hyderabad,NaN,"Residential, Rural and other Areas",6.3,14.7,NaN,NaN,NaN,NaN,01-03-1990
4,151,March - M031990,Andhra Pradesh,Hyderabad,NaN,Industrial Area,4.7,7.5,NaN,NaN,NaN,NaN,01-03-1990

In [25]:
ds.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 435742 entries, 0 to 435741
Data columns (total 13 columns):
 #   Column                       Non-Null Count   Dtype
---  ------                       --------------   -----
 0   stn_code                     291665 non-null  object
 1   sampling_date                435739 non-null  object
 2   state                        435742 non-null  object
 3   location                     435739 non-null  object
 4   agency                       286261 non-null  object
 5   type                         430349 non-null  object
 6   so2                          401096 non-null  float64
 7   no2                          419509 non-null  float64
 8   rspm                         395520 non-null  float64
 9   spm                          198355 non-null  float64
 10  location_monitoring_station  408251 non-null  object
 11  pm2_5                        9314 non-null    float64
 12  date                         435735 non-null  object
dtypes: float64(5), object(8)
memory usage: 43.2+ MB

In [26]:
ds.dropna()

Empty DataFrame
Columns: [stn_code, sampling_date, state, location, agency, type, so2, no2, rspm, spm, location_monitoring_station, pm2_5, date]
Index: []

In [27]:


ds.columns

Index(['stn_code', 'sampling_date', 'state', 'location', 'agency', 'type',
       'so2', 'no2', 'rspm', 'spm', 'location_monitoring_station', 'pm2_5',
       'date'],
      dtype='object')

In [28]:
ds.columns

Index(['stn_code', 'sampling_date', 'state', 'location', 'agency', 'type',
       'so2', 'no2', 'rspm', 'spm', 'location_monitoring_station', 'pm2_5',
       'date'],
      dtype='object')

In [29]:
ds_heart = pd.read_csv(r"E:\dataset\heart.csv")

In [30]:
ds_heart.columns

Index(['age', 'sex', 'cp', 'trestbps', 'chol', 'fbs', 'restecg', 'thalach',
       'exang', 'oldpeak', 'slope', 'ca', 'thal', 'target'],
      dtype='object')

In [31]:
ds.columns = ds.columns.str.strip()

In [32]:
ds_heart.columns = ds_heart.columns.str.strip()

In [33]:
ds.columns

Index(['stn_code', 'sampling_date', 'state', 'location', 'agency', 'type',
       'so2', 'no2', 'rspm', 'spm', 'location_monitoring_station', 'pm2_5',
       'date'],
      dtype='object')

In [34]:
ds1 = ds.loc[111:999, ['sampling_date', 'state', 'so2', 'no2']]

ds2 = ds.iloc[[1,3,5,2,4,22,43,54,67,7,8,9,50,10,11]]

print(ds1.head())

print(ds2.head())

      sampling_date           state   so2   no2
111  June - M061992  Andhra Pradesh   4.9  20.8
112  June - M061992  Andhra Pradesh   NaN   NaN
113  June - M061992  Andhra Pradesh  11.2  22.4
114  June - M061992  Andhra Pradesh   4.5  33.9
115  June - M061992  Andhra Pradesh   6.2  27.6
  stn_code       sampling_date           state   location agency  \
1      151  February - M021990  Andhra Pradesh  Hyderabad    NaN
3      150     March - M031990  Andhra Pradesh  Hyderabad    NaN
5      152     March - M031990  Andhra Pradesh  Hyderabad    NaN
2      152  February - M021990  Andhra Pradesh  Hyderabad    NaN
4      151     March - M031990  Andhra Pradesh  Hyderabad    NaN

                                 type  so2   no2  rspm  spm  \
1                     Industrial Area  3.1   7.0   NaN  NaN
3  Residential, Rural and other Areas  6.3  14.7   NaN  NaN
5  Residential, Rural and other Areas  6.4  25.7   NaN  NaN
2  Residential, Rural and other Areas  6.2  28.5   NaN  NaN
4                     Industrial Area  4.7   7.5   NaN  NaN

  location_monitoring_station  pm2_5        date
1                         NaN    NaN  01-02-1990
3                         NaN    NaN  01-03-1990
5                         NaN    NaN  01-03-1990
2                         NaN    NaN  01-02-1990
4                         NaN    NaN  01-03-1990

In [35]:
print(ds.columns)

Index(['stn_code', 'sampling_date', 'state', 'location', 'agency', 'type',
       'so2', 'no2', 'rspm', 'spm', 'location_monitoring_station', 'pm2_5',
       'date'],
      dtype='object')

In [36]:
ds_integration = pd.concat([ds1,ds2])

In [37]:
ds_integration

,sampling_date,state,so2,no2,stn_code,location,agency,type,rspm,spm,location_monitoring_station,pm2_5,date
111,June - M061992,Andhra Pradesh,4.9,20.8,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
112,June - M061992,Andhra Pradesh,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
113,June - M061992,Andhra Pradesh,11.2,22.4,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
114,June - M061992,Andhra Pradesh,4.5,33.9,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
115,June - M061992,Andhra Pradesh,6.2,27.6,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...
8,April - M041990,Andhra Pradesh,4.2,23.0,152,Hyderabad,NaN,"Residential, Rural and other Areas",NaN,NaN,NaN,NaN,01-04-1990
9,May - M051990,Andhra Pradesh,4.0,8.9,151,Hyderabad,NaN,Industrial Area,NaN,NaN,NaN,NaN,01-05-1990
50,August - M081991,Andhra Pradesh,8.5,12.5,150,Hyderabad,NaN,"Residential, Rural and other Areas",NaN,119.0,NaN,NaN,01-08-1991
10,May - M051990,Andhra Pradesh,3.6,18.6,152,Hyderabad,NaN,"Residential, Rural and other Areas",NaN,NaN,NaN,NaN,01-05-1990
11,June - M061990,Andhra Pradesh,3.9,14.1,150,Hyderabad,NaN,"Residential, Rural and other Areas",NaN,133.0,NaN,NaN,01-06-1990

In [38]:
ds_integration.transpose()

,111,112,113,114,115,116,117,118,119,120,...,22,43,54,67,7,8,9,50,10,11
sampling_date,June - M061992,June - M061992,June - M061992,June - M061992,June - M061992,June - M061992,June - M061992,July - M071992,July - M071992,July - M071992,...,September - M091990,May - M051991,September - M091991,January - M011992,April - M041990,April - M041990,May - M051990,August - M081991,May - M051990,June - M061990
state,Andhra Pradesh,Andhra Pradesh,Andhra Pradesh,Andhra Pradesh,Andhra Pradesh,Andhra Pradesh,Andhra Pradesh,Andhra Pradesh,Andhra Pradesh,Andhra Pradesh,...,Andhra Pradesh,Andhra Pradesh,Andhra Pradesh,Andhra Pradesh,Andhra Pradesh,Andhra Pradesh,Andhra Pradesh,Andhra Pradesh,Andhra Pradesh,Andhra Pradesh
so2,4.9,NaN,11.2,4.5,6.2,7.3,7.3,13.0,5.2,6.5,...,8.1,12.3,13.3,35.8,4.7,4.2,4.0,8.5,3.6,3.9
no2,20.8,NaN,22.4,33.9,27.6,9.0,13.0,68.0,13.1,23.3,...,17.8,38.6,11.9,12.5,8.7,23.0,8.9,12.5,18.6,14.1
stn_code,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,152,152,151,203,151,152,151,150,152,150
location,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,Hyderabad,Hyderabad,Hyderabad,Hyderabad,Hyderabad,Hyderabad,Hyderabad,Hyderabad,Hyderabad,Hyderabad
agency,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,Andhra Pradesh Pollution Control Board,NaN,NaN,NaN,NaN,NaN,NaN
type,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,"Residential, Rural and other Areas","Residential, Rural and other Areas",Industrial Area,NaN,Industrial Area,"Residential, Rural and other Areas",Industrial Area,"Residential, Rural and other Areas","Residential, Rural and other Areas","Residential, Rural and other Areas"
rspm,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
spm,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,167.0,219.0,56.0,261.0,NaN,NaN,NaN,119.0,NaN,133.0
location_monitoring_station,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
pm2_5,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
date,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,01-09-1990,01-05-1991,01-09-1991,01-01-1992,01-04-1990,01-04-1990,01-05-1990,01-08-1991,01-05-1990,01-06-1990

In [39]:
ds = ds.drop(columns="so2")

In [40]:
ds_merged = pd.concat([ds,ds_heart])
ds_merged

,stn_code,sampling_date,state,location,agency,type,no2,rspm,spm,location_monitoring_station,...,chol,fbs,restecg,thalach,exang,oldpeak,slope,ca,thal,target
0,150,February - M021990,Andhra Pradesh,Hyderabad,NaN,"Residential, Rural and other Areas",17.4,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,151,February - M021990,Andhra Pradesh,Hyderabad,NaN,Industrial Area,7.0,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,152,February - M021990,Andhra Pradesh,Hyderabad,NaN,"Residential, Rural and other Areas",28.5,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,150,March - M031990,Andhra Pradesh,Hyderabad,NaN,"Residential, Rural and other Areas",14.7,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,151,March - M031990,Andhra Pradesh,Hyderabad,NaN,Industrial Area,7.5,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
298,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,241.0,0.0,1.0,123.0,1.0,0.2,1.0,0.0,3.0,0.0
299,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,264.0,0.0,1.0,132.0,0.0,1.2,1.0,0.0,3.0,0.0
300,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,193.0,1.0,1.0,141.0,0.0,3.4,1.0,2.0,3.0,0.0
301,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,131.0,0.0,1.0,115.0,1.0,1.2,1.0,1.0,3.0,0.0
302,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,236.0,0.0,0.0,174.0,0.0,0.0,1.0,1.0,2.0,0.0

In [41]:
ds.columns

Index(['stn_code', 'sampling_date', 'state', 'location', 'agency', 'type',
       'no2', 'rspm', 'spm', 'location_monitoring_station', 'pm2_5', 'date'],
      dtype='object')

In [42]:
ds['no2'].unique()

array([ 17.4,   7. ,  28.5, ..., 319. , 304. , 200. ], shape=(6865,))

In [43]:
ds.no2.value_counts()

no2
13.0     9447
14.0     9386
5.0      8738
15.0     8693
12.0     8490
         ...
234.0       1
256.0       1
227.0       1
218.0       1
226.0       1
Name: count, Length: 6864, dtype: int64